// Auto-generated by npm run sync:moderation — do not edit manually.
// Zdroj: src/config/categories.ts

const CATEGORY_AI_PROMPTS: Record<string, string> = {
  "zbozi": "Analyzuj nabízené zboží. cleanedDescription: úvod (co prodáváš + cena v textu) a sekce Parametry s odrážkami (nájezd, rozměry, materiál, výbava, stav…). Ve formuláři dostaneš stav — u „Poškozené / na díly“ bez rozsahu vady se ptej. Doplňující otázky jen na chybějící zásadní parametry. Na cenu se neptej, pokud je ve formuláři.",
  "zbozi/potraviny-domaci": "Uživatel nabízí potraviny nebo domácí jedlé výrobky.\n\nOčekávej jedlé věci jako med, marmelády, sirupy, pečivo, ovoce, zeleninu, vejce, bylinky, koření, domácí zavařeniny nebo jiné potraviny a nápoje.\nPokud text nebo fotografie zjevně ukazují nejedlý produkt (např. elektroniku, router, WiFi extender, nábytek, oblečení, autodíl, nářadí), vrať REJECTED s důvodem, že inzerát je zařazený do špatné kategorie a má se přesunout jinam.\nPokud jde o potravinu, zeptej se jen na zásadní chybějící údaje jako druh, množství, forma balení, trvanlivost nebo alergeny, pokud jsou relevantní.",
  "zbozi/elektronika": "Úvod + Parametry (model, stav, výbava, baterie u mobilů…). Dotazník jen pokud chybí klíčové parametry.",
  "zbozi/auta-moto": "Úvod + Parametry (rok, nájezd, motorizace, STK, výbava, stav). Na cenu se neptej, pokud je ve formuláři — cenu dej do úvodu. Dotazník jen na chybějící údaje.",
  "zbozi/moda-obleceni": "Uživatel prodává módu a oblečení.\n\nSPODNÍ A INTIMNÍ PRÁDLO — povinná pravidla:\n- Fotografie musí ukazovat pouze věc (věšák, flat lay, detail materiálu), ne osobu v prádle, postel ani boudoir styl.\n- V popisu nebo Parametrech musí být velikost; doporuč značku a stav.\n- Zamítnout (REJECTED, sexual_services), pokud foto sexualizuje osobu nebo inzerát působí jako nabídka sexuální služby místo prodeje věci.\n- Pro předání piš „osobní předání po domluvě“ nebo „vyzvednutí po domluvě“, NIKDY „osobní prohlídka“ (to platí jen u nemovitostí).\n\nObecně: pokud z textu či fotek NENÍ jasná VELIKOST nebo ZNAČKA, vygeneruj maximálně 2 stručné otázky. Na volitelné parametry (materiál, sezóna) se ptej jen pokud text neobsahuje téměř nic.",
  "sluzby": "Uživatel nabízí službu (ne prodává zboží). Cena ve formuláři je buď hodinová sazba (Kč/h), orientační cena za celou zakázku, nebo „Dohodou“ — respektuj typ z formuláře, neptej se znovu na cenu.\n\nPokud v textu chybí lokalita/dojezd (kde službu poskytuje) nebo informace o materiálu (zda je v ceně), zeptej se na to jednou či dvěma přátelskými otázkami. Pokud je text dostatečně jasný, neptej se na nic.\n\nPovinná pravidla — typ inzerenta (priorita před ostatními otázkami):\nZájemce musí vědět, zda inzerent jedná jako soukromá osoba, nebo v rámci podnikání (Podnikatel — firma, OSVČ apod.).\nLogika: buď je jednoznačné v textu nebo na fotkách → zapiš do Parametrů konkrétní hodnotu (např. • Typ inzerenta: soukromá osoba nebo • Typ inzerenta: Podnikatel) a neptej se; nebo chybí / je nejasné → NEEDS_QUESTIONS (nikdy nehádej).\nU NEEDS_QUESTIONS neuváděj v Parametrech řádek Typ inzerenta s placeholderem (…, -, prázdně) — chybějící typ ptej jen v dotazníku; odpověď se doplní automaticky.\nPtej se jen pokud z textu/fotek nevyplývá typ (paramLabel: „Typ inzerenta“; label např. „Inzerujete jako soukromá osoba, nebo v rámci podnikání (firma/OSVČ)?“).\nJednoznačné formulace (otázku neopakuj): „soukromě“, „osobně“, „jako majitel“, název firmy, „s.r.o.“, „v.o.s.“, „OSVČ“, „IČO“, „realitní kancelář“, „RK“.\nJe-li Podnikatel, v Parametrech uveď firmu a IČO, pokud jsou v textu nebo na fotkách; chybí-li IČO u zjevného Podnikatele, ptej se (paramLabel: „IČO“; label např. „Jaké je vaše IČO?“).",
  "sluzby/pece-zahrada": "Uživatel nabízí službu v domácnosti (úklid, hlídání, drobné práce), péči nebo zahradu. U úklidu doplň rozsah (byt, dům, kancelář), frekvenci a zda je materiál v ceně. U zahrady rozsah a dojezd.",
  "udalost": "Analyzuj akci. Ve formuláři může být datum konání — na to se znovu neptej. Kritické parametry jsou: DATUM (pokud chybí ve formuláři i v textu), ČAS a LOKALITA. Pokud některý chybí, vygeneruj cílené otázky. U opakovaných akcí chtěj upřesnit frekvenci (např. „Které dny v týdnu akce platí?“).",
  "nemovitost": "Uživatel nabízí nemovitost — typ transakce (Prodej / Pronájem) a podkategorie (byt, dům, pozemek…) jsou ve formuláři. Skenuj text a všechny fotky.\n\nPovinná pravidla — zadavatel a provize RK (priorita před ostatními otázkami):\nKupující/nájemce musí vždy vědět, zda inzeruje majitel (soukromá osoba), nebo realitní kancelář, a jak je to s provizí RK.\nLogika: buď je vše jednoznačné v textu nebo na fotkách → zapiš do Parametrů (• Zadavatel: …, • Provize RK: …) a neptej se; nebo něco chybí / je nejasné → NEEDS_QUESTIONS (nikdy nehádej).\n\n1) Zadavatel — ptej se jen pokud z textu/fotek nevyplývá, zda jde o majitele (soukromá inzerce), nebo realitní kancelář. (paramLabel: „Zadavatel“; label např. „Inzerujete jako majitel, nebo za realitní kancelář?“)\n2) Provize RK — ptej se vždy, když: (a) je v textu zmíněna realitka / RK / makléř, ale není jasné, zda je provize v ceně, nebo navíc (hradí ji kupující/nájemce); (b) není jasné, zda jde o soukromou inzerci, nebo přes RK; (c) RK je potvrzená, ale chybí info o provizi. (paramLabel: „Provize RK“; label např. „Je provize realitní kanceláře zahrnutá v uvedené ceně, nebo se platí navíc?“)\nU jednoznačné soukromé inzerce bez RK zapiš do Parametrů „Provize RK: bez provize“ — na provizi se neptej.\nJednoznačné formulace v textu (otázku neopakuj): „soukromý prodej“, „prodám vlastní“, „bez RK“, „realitka“, „RK“, „včetně provize“, „provize v ceně“, „provize navíc“, „provizi hradí kupující“, „provizi hradí nájemce“.\n\nDalší kritické údaje dle kontextu: dispozice (např. 2+kk), plocha v m²; u pronájmu též kauce a měsíční poplatky — ptej jen pokud zcela chybí. Na detaily (patro, výtah, parkování) se ptej jen při velmi stručném popisu. Celkem max 5 otázek.",
  "prace": "Uživatel nabízí práci/brigádu. Zaměř se na: termín nástupu, požadavky na pracovníka a odměnu. Chybí-li tyto informace, zeptej se na ně. NEPOKOUŠEJ SE v tomto kroku upravovat nebo cenzurovat telefonní čísla a e-maily, to řeší systém jinde.\n\nPovinná pravidla — typ inzerenta (priorita před ostatními otázkami):\nZájemce musí vědět, zda inzerent jedná jako soukromá osoba, nebo v rámci podnikání (Podnikatel — firma, OSVČ apod.).\nLogika: buď je jednoznačné v textu nebo na fotkách → zapiš do Parametrů konkrétní hodnotu (např. • Typ inzerenta: soukromá osoba nebo • Typ inzerenta: Podnikatel) a neptej se; nebo chybí / je nejasné → NEEDS_QUESTIONS (nikdy nehádej).\nU NEEDS_QUESTIONS neuváděj v Parametrech řádek Typ inzerenta s placeholderem (…, -, prázdně) — chybějící typ ptej jen v dotazníku; odpověď se doplní automaticky.\nPtej se jen pokud z textu/fotek nevyplývá typ (paramLabel: „Typ inzerenta“; label např. „Inzerujete jako soukromá osoba, nebo v rámci podnikání (firma/OSVČ)?“).\nJednoznačné formulace (otázku neopakuj): „soukromě“, „osobně“, „jako majitel“, název firmy, „s.r.o.“, „v.o.s.“, „OSVČ“, „IČO“, „realitní kancelář“, „RK“.\nJe-li Podnikatel, v Parametrech uveď firmu a IČO, pokud jsou v textu nebo na fotkách; chybí-li IČO u zjevného Podnikatele, ptej se (paramLabel: „IČO“; label např. „Jaké je vaše IČO?“)."
};

export const VALID_CATEGORY_TYPES = ["zbozi","sluzby","udalost","nemovitost","prace"] as const;

export const VALID_SUBCATEGORY_SLUGS: Record<string, readonly string[]> = {
  "zbozi": [
    "potraviny-domaci",
    "kola-sport",
    "nabytek-domacnost",
    "elektronika",
    "auta-moto",
    "moda-obleceni",
    "ostatni"
  ],
  "sluzby": [
    "remeslo-opravy",
    "stehovani-doprava",
    "pece-zahrada",
    "ostatni"
  ],
  "udalost": [
    "koncert",
    "narozeniny",
    "opekani",
    "sport",
    "workshop",
    "setkani",
    "ostatni"
  ],
  "nemovitost": [
    "byty",
    "domy",
    "pozemky",
    "chata-chalupa",
    "komercni",
    "ostatni"
  ],
  "prace": [
    "brigady-jednorazove",
    "retail-pohostinstvi",
    "administrativa",
    "it-digital",
    "remeslo-stavba",
    "pece-zahrada",
    "ostatni"
  ]
};

export function assertValidCategoryPair(
  categoryType: string,
  subcategorySlug: string,
): void {
  if (
    !(VALID_CATEGORY_TYPES as readonly string[]).includes(categoryType)
  ) {
    throw new Error("INVALID_CATEGORY_TYPE");
  }

  const allowed = VALID_SUBCATEGORY_SLUGS[categoryType];
  if (!allowed?.includes(subcategorySlug)) {
    throw new Error("INVALID_SUBCATEGORY_SLUG");
  }
}

export function resolveCategoryAiPrompt(
  categoryType: string,
  subcategorySlug: string,
): string | undefined {
  const subKey = `${categoryType}/${subcategorySlug}`;
  const parts = [
    CATEGORY_AI_PROMPTS[subKey],
    CATEGORY_AI_PROMPTS[categoryType],
  ].filter((part): part is string => Boolean(part));
  return parts.length > 0 ? parts.join("\n\n") : undefined;
}
