// Auto-generated by npm run sync:moderation — do not edit manually.
// Zdroj: src/config/categories.ts

const CATEGORY_AI_PROMPTS: Record<string, string> = {
  "zbozi": "Analyzuj nabízené zboží. cleanedDescription: úvod (co prodáváš + cena v textu) a sekce Parametry s odrážkami (nájezd, rozměry, materiál, výbava, stav…). Ve formuláři dostaneš stav — u „Poškozené / na díly“ bez rozsahu vady se ptej. Doplňující otázky jen na chybějící zásadní parametry. Na cenu se neptej, pokud je ve formuláři.",
  "zbozi/elektronika": "Úvod + Parametry (model, stav, výbava, baterie u mobilů…). Dotazník jen pokud chybí klíčové parametry.",
  "zbozi/auta-moto": "Úvod + Parametry (rok, nájezd, motorizace, STK, výbava, stav). Na cenu se neptej, pokud je ve formuláři — cenu dej do úvodu. Dotazník jen na chybějící údaje.",
  "zbozi/moda-obleceni": "Uživatel prodává módu. Pokud z textu či fotek NENÍ jasná VELIKOST nebo ZNAČKA, vygeneruj maximálně 2 stručné, lidské otázky (např. „Jaká je to velikost?“). Na volitelné parametry (materiál, sezóna) se ptej, jen pokud text neobsahuje téměř nic.",
  "sluzby": "Uživatel nabízí službu. Pokud v textu chybí lokalita/dojezd (kde službu poskytuje) nebo informace o materiálu (zda je v ceně), zeptej se na to jednou či dvěma přátelskými otázkami. Pokud je text dostatečně jasný, neptej se na nic.",
  "udalost": "Analyzuj akci. Ve formuláři může být datum konání — na to se znovu neptej. Kritické parametry jsou: DATUM (pokud chybí ve formuláři i v textu), ČAS a LOKALITA. Pokud některý chybí, vygeneruj cílené otázky. U opakovaných akcí chtěj upřesnit frekvenci (např. „Které dny v týdnu akce platí?“).",
  "nemovitost": "Uživatel nabízí nemovitost — typ transakce (Prodej / Pronájem) je ve formuláři. Skenuj text a fotky.\n\nVŽDY se doplňujícími otázkami ověř (pokud to z textu/fotek nevyplývá), parametry pak uveď v sekci Parametry:\n1) Zadavatel: soukromá osoba, nebo realitní kancelář? (paramLabel: „Zadavatel“; label např. „Inzerujete jako soukromá osoba, nebo za realitní kancelář?“)\n2) Cena a provize RK: je uvedená cena včetně provize pro realitní kancelář? (paramLabel: „Provize v ceně“; u pronájmu můžeš formulovat i poplatky RK — label např. „Je cena včetně provize / poplatků realitní kanceláře?“)\nPokud uživatel už jednoznačně napsal „soukromý prodej“, „bez RK“, „realitka“, „RK“, „včetně provize“ apod., danou otázku neopakuj.\n\nDalší kritické údaje dle kontextu: dispozice (např. 2+kk), plocha v m²; u pronájmu též kauce a měsíční poplatky — ptej jen pokud zcela chybí. Na detaily (patro, výtah, parkování) se ptej jen při velmi stručném popisu. Celkem max 5 otázek.",
  "prace": "Uživatel nabízí práci/brigádu. Zaměř se na: termín nástupu, požadavky na pracovníka a odměnu. Chybí-li tyto informace, zeptej se na ně. NEPOKOUŠEJ SE v tomto kroku upravovat nebo cenzurovat telefonní čísla a e-maily, to řeší systém jinde."
};

export const VALID_CATEGORY_TYPES = ["zbozi","sluzby","udalost","nemovitost","prace"] as const;

export const VALID_SUBCATEGORY_SLUGS: Record<string, readonly string[]> = {
  "zbozi": [
    "potraviny-domaci",
    "kola-sport",
    "nabytek-domacnost",
    "elektronika",
    "auta-moto",
    "moda-obleceni",
    "ostatni"
  ],
  "sluzby": [
    "remeslo-opravy",
    "stehovani-doprava",
    "pece-zahrada",
    "ostatni"
  ],
  "udalost": [
    "koncert",
    "narozeniny",
    "opekani",
    "sport",
    "workshop",
    "setkani",
    "ostatni"
  ],
  "nemovitost": [
    "byty",
    "domy",
    "pozemky",
    "chata-chalupa",
    "komercni",
    "ostatni"
  ],
  "prace": [
    "brigady-jednorazove",
    "retail-pohostinstvi",
    "administrativa",
    "it-digital",
    "remeslo-stavba",
    "pece-zahrada",
    "ostatni"
  ]
};

export function assertValidCategoryPair(
  categoryType: string,
  subcategorySlug: string,
): void {
  if (
    !(VALID_CATEGORY_TYPES as readonly string[]).includes(categoryType)
  ) {
    throw new Error("INVALID_CATEGORY_TYPE");
  }

  const allowed = VALID_SUBCATEGORY_SLUGS[categoryType];
  if (!allowed?.includes(subcategorySlug)) {
    throw new Error("INVALID_SUBCATEGORY_SLUG");
  }
}

export function resolveCategoryAiPrompt(
  categoryType: string,
  subcategorySlug: string,
): string | undefined {
  const subKey = `${categoryType}/${subcategorySlug}`;
  const parts = [
    CATEGORY_AI_PROMPTS[subKey],
    CATEGORY_AI_PROMPTS[categoryType],
  ].filter((part): part is string => Boolean(part));
  return parts.length > 0 ? parts.join("\n\n") : undefined;
}
