// Auto-generated by npm run sync:moderation — do not edit manually.
// Source: src/config/app.ts + src/config/moderation/index.ts

export const LISTING_DESCRIPTION_MAX_LENGTH = 2000;

/** Rezerva pro odpovědi z dotazníku (NEEDS_QUESTIONS) — drž v sync s app.ts */
export const MODERATION_DESCRIPTION_QA_RESERVE = 400;

/** Max. velikost jedné fotky po dekódování base64 (M7). */
export const MODERATION_IMAGE_MAX_BYTES = 512000;

/** Max. součet velikostí fotek po dekódování (M7). */
export const MODERATION_IMAGES_MAX_TOTAL_BYTES = 2097152;

export const NSFW_NUDITY_RAW_THRESHOLD = 0.6;

export const NSFW_NUDITY_PARTIAL_THRESHOLD = 0.8;

export const SIGHTENGINE_FETCH_TIMEOUT_MS = 5000;

export const HARD_REJECT_AUTOBAN_THRESHOLD = 3;

export const HARD_REJECT_WINDOW_MS = 86400000;

export const MODERATION_EVIDENCE_BUCKET = "moderation-evidence";
