// Auto-generated by npm run sync:moderation — do not edit manually.
// Zdroj: src/config/categories-goods.ts + goods-categories.ts

export const GOODS_CATEGORY_TYPES = ["auto","detsky","dum","elektro","moda","sport","hobby","ostatni"] as const;

export const GOODS_SUBCATEGORY_SLUGS: Record<string, readonly string[]> = {
  "auto": [
    "osobni-auta",
    "motorky",
    "dily-prislusenstvi",
    "ostatni"
  ],
  "detsky": [
    "detske-obleceni-obuv",
    "kocarky-sedacky-nabytek",
    "hracky-miminka",
    "ostatni"
  ],
  "dum": [
    "nabytek-doplnky",
    "zahrada-naradi",
    "potraviny-domaci",
    "ostatni"
  ],
  "elektro": [
    "mobily",
    "pc",
    "tv-foto-audio",
    "spotrebice",
    "ostatni"
  ],
  "moda": [
    "damske-panske",
    "boty-doplnky",
    "ostatni"
  ],
  "sport": [
    "kola-kolobezky",
    "zimni-sport",
    "ostatni"
  ],
  "hobby": [
    "knihy-hry-hudba",
    "sberatelstvi-umeni",
    "ostatni"
  ],
  "ostatni": [
    "ostatni"
  ]
};

/** Closed vocabulary text pro Gemini system prompt (suggest-from-photos). */
export const GOODS_TAXONOMY_PROMPT_BLOCK = "- auto (Auto) → [osobni-auta (Osobní auta), motorky (Motorky), dily-prislusenstvi (Díly a příslušenství), ostatni (Ostatní)]\n- detsky (Dětské) → [detske-obleceni-obuv (Dětské oblečení a obuv), kocarky-sedacky-nabytek (Kočárky, sedačky a nábytek), hracky-miminka (Hračky a pro miminka), ostatni (Ostatní)]\n- dum (Dům a zahrada) → [nabytek-doplnky (Nábytek a doplňky), zahrada-naradi (Zahrada a nářadí), potraviny-domaci (Potraviny a domácí výrobky), ostatni (Ostatní)]\n- elektro (Elektronika) → [mobily (Mobily), pc (Počítače), tv-foto-audio (TV, foto a audio), spotrebice (Spotřebiče), ostatni (Ostatní)]\n- moda (Móda) → [damske-panske (Dámské a pánské), boty-doplnky (Boty a doplňky), ostatni (Ostatní)]\n- sport (Sport) → [kola-kolobezky (Kola a koloběžky), zimni-sport (Zimní sport), ostatni (Ostatní)]\n- hobby (Hobby) → [knihy-hry-hudba (Knihy, hry a hudba), sberatelstvi-umeni (Sběratelství a umění), ostatni (Ostatní)]\n- ostatni (Ostatní) → [ostatni (Ostatní)]";

export function isGoodsCategoryType(categoryType: string): boolean {
  return (GOODS_CATEGORY_TYPES as readonly string[]).includes(categoryType);
}

export function isValidGoodsSubcategory(
  categoryType: string,
  subcategorySlug: string | null,
): boolean {
  if (!subcategorySlug) return false;
  const allowed = GOODS_SUBCATEGORY_SLUGS[categoryType];
  return Boolean(allowed?.includes(subcategorySlug));
}
