export const GDPR_RETENTION_DELETE_AFTER_DAYS = 90;
export const GDPR_RETENTION_WARNING_BEFORE_DAYS = 7;

export const GDPR_RETENTION_WARNING_AFTER_DAYS =
  GDPR_RETENTION_DELETE_AFTER_DAYS - GDPR_RETENTION_WARNING_BEFORE_DAYS;

export const GDPR_RETENTION_REASON_CODE = "gdpr_retention";
