/**
 * Exportuje mapu aiPrompt z categories.ts pro Edge Function (server-side only).
 * Spouští: npm run sync:moderation
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CATEGORIES } from "../src/config/categories.ts";
import { GOODS_CATEGORIES } from "../src/config/categories-goods.ts";
import { GOODS_CATEGORY_TYPES } from "../src/config/goods-categories.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(
  root,
  "supabase/functions/_shared/moderation/category-prompts.ts",
);
const goodsTaxonomyTarget = join(
  root,
  "supabase/functions/_shared/moderation/goods-taxonomy.ts",
);

const promptMap: Record<string, string> = {};
const subcategoriesByType: Record<string, string[]> = {};

for (const cat of CATEGORIES) {
  subcategoriesByType[cat.type] = cat.subcategories.map((s) => s.slug);
  if (cat.aiPrompt) {
    promptMap[cat.type] = cat.aiPrompt;
  }
  for (const sub of cat.subcategories) {
    if (sub.aiPrompt) {
      promptMap[`${cat.type}/${sub.slug}`] = sub.aiPrompt;
    }
  }
}

const categoryTypes = CATEGORIES.map((c) => c.type);

const file = `// Auto-generated by npm run sync:moderation — do not edit manually.
// Zdroj: src/config/categories.ts

const CATEGORY_AI_PROMPTS: Record<string, string> = ${JSON.stringify(promptMap, null, 2)};

export const VALID_CATEGORY_TYPES = ${JSON.stringify(categoryTypes)} as const;

export const VALID_SUBCATEGORY_SLUGS: Record<string, readonly string[]> = ${JSON.stringify(subcategoriesByType, null, 2)};

export function assertValidCategoryPair(
  categoryType: string,
  subcategorySlug: string,
): void {
  if (
    !(VALID_CATEGORY_TYPES as readonly string[]).includes(categoryType)
  ) {
    throw new Error("INVALID_CATEGORY_TYPE");
  }

  const allowed = VALID_SUBCATEGORY_SLUGS[categoryType];
  if (!allowed?.includes(subcategorySlug)) {
    throw new Error("INVALID_SUBCATEGORY_SLUG");
  }
}

export function resolveCategoryAiPrompt(
  categoryType: string,
  subcategorySlug: string,
): string | undefined {
  const subKey = \`\${categoryType}/\${subcategorySlug}\`;
  const parts = [
    CATEGORY_AI_PROMPTS[subKey],
    CATEGORY_AI_PROMPTS[categoryType],
  ].filter((part): part is string => Boolean(part));
  return parts.length > 0 ? parts.join("\\n\\n") : undefined;
}
`;

writeFileSync(target, file, "utf8");
console.log("Exported category prompts:", target);

const goodsSubcategories: Record<string, { slug: string; label: string }[]> =
  {};
const taxonomyLines: string[] = [];

for (const cat of GOODS_CATEGORIES) {
  goodsSubcategories[cat.type] = cat.subcategories.map((s) => ({
    slug: s.slug,
    label: s.label,
  }));
  const subList = cat.subcategories
    .map((s) => `${s.slug} (${s.label})`)
    .join(", ");
  taxonomyLines.push(`- ${cat.type} (${cat.label}) → [${subList}]`);
}

const goodsFile = `// Auto-generated by npm run sync:moderation — do not edit manually.
// Zdroj: src/config/categories-goods.ts + goods-categories.ts

export const GOODS_CATEGORY_TYPES = ${JSON.stringify([...GOODS_CATEGORY_TYPES])} as const;

export const GOODS_SUBCATEGORY_SLUGS: Record<string, readonly string[]> = ${JSON.stringify(
  Object.fromEntries(
    GOODS_CATEGORIES.map((c) => [
      c.type,
      c.subcategories.map((s) => s.slug),
    ]),
  ),
  null,
  2,
)};

/** Closed vocabulary text pro Gemini system prompt (suggest-from-photos). */
export const GOODS_TAXONOMY_PROMPT_BLOCK = ${JSON.stringify(taxonomyLines.join("\n"))};

export function isGoodsCategoryType(categoryType: string): boolean {
  return (GOODS_CATEGORY_TYPES as readonly string[]).includes(categoryType);
}

export function isValidGoodsSubcategory(
  categoryType: string,
  subcategorySlug: string | null,
): boolean {
  if (!subcategorySlug) return false;
  const allowed = GOODS_SUBCATEGORY_SLUGS[categoryType];
  return Boolean(allowed?.includes(subcategorySlug));
}
`;

writeFileSync(goodsTaxonomyTarget, goodsFile, "utf8");
console.log("Exported goods taxonomy:", goodsTaxonomyTarget);
